
// WTF why do I have to prefix this with include while other tests don't?
// Cmake is set up the same for both handwritten and autogenerated ones
#include <include/gtest/gtest.h>

#define _USE_MATH_DEFINES
#include <cmath>

#include "math/fast_log_64.hh"

class FastLogComputeTest : public testing::TestWithParam<double> {};

void compare(double input, double tolerance) {

  double computed = fast_ln_out_of_line(input);

  double expected = std::log(input);

  double rel_diff = std::abs((computed - expected) / expected);

  EXPECT_LE(rel_diff, tolerance)
      << "fast ln of " << input << " is " << computed << ", expected "
      << expected << ", relative difference " << rel_diff
      << " less than tolerance " << tolerance;
}

TEST_P(FastLogComputeTest, TestComputeLn) { compare(GetParam(), 1e-3); }

TEST(FastLogTest, TestFastLogZeroAtOne) {
  double computed = fast_ln_out_of_line(1.0);

  EXPECT_EQ(computed, 0.0) << "fast ln of 1.0 is " << computed
                           << ", expected exactly 0.0";
}

INSTANTIATE_TEST_SUITE_P(FastLogTest, FastLogComputeTest,
                         ::testing::Values(0.5, 1.1, 2.0, M_E, 5.0, 10.0, 100.0,
                                           1000.0, 10000.0) // base
);