#include "signals/multi_stream_book/level_tracker.hh"

// WTF why do I have to prefix this with include while other tests don't?
// Cmake is set up the same for both handwritten and autogenerated ones
#include <include/gtest/gtest.h>

#include <cmath>

// Test that if there's no impulse, we get NaN

TEST(LevelTrackingMetadata, TestCtorBuilds) { LevelTracker l; }